spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: asdqwe
    driver-class-name: org.postgresql.Driver
    initialization-mode: always